# Generated by Django 5.2.2 on 2025-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('work_time', models.CharField(max_length=50, verbose_name='Work time')),
                ('info', models.TextField(verbose_name='Information')),
                ('map_address', models.URLField(verbose_name='Map address')),
                ('status', models.BooleanField(verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('status', models.BooleanField(verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='sub_category_photos/', verbose_name='Photo')),
                ('status', models.BooleanField(verbose_name='State')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='sub_category_photos/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('status', models.BooleanField(verbose_name='State')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapapp.sub_category')),
            ],
        ),
    ]
