# Generated by Django 5.2.2 on 2025-06-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product_photos/', verbose_name='Photo'),
        ),
    ]
