# Generated by Django 5.2.2 on 2025-06-10 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapapp', '0002_alter_branch_info_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\+]998[0-9](9)$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapapp.sub_category', verbose_name='Sub category'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapapp.category', verbose_name='Category'),
        ),
    ]
