# Generated by Django 5.2.1 on 2025-05-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nomi')),
                ('photo', models.ImageField(upload_to='category_photos/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Batafsil')),
                ('status', models.CharField(choices=[('archive', 'Arxiv'), ('active', 'Faol')], max_length=50, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer1', models.CharField(max_length=255, verbose_name='1-javob')),
                ('answer2', models.CharField(max_length=255, verbose_name='2-javob')),
                ('answer3', models.CharField(max_length=255, verbose_name='3-javob')),
                ('true_answer', models.CharField(choices=[('answer1', models.CharField(max_length=255, verbose_name='1-javob')), ('answer2', models.CharField(max_length=255, verbose_name='2-javob')), ('answer3', models.CharField(max_length=255, verbose_name='3-javob'))], max_length=50, verbose_name='Javob')),
                ('status', models.CharField(choices=[('archive', 'Arxiv'), ('active', 'Faol')], max_length=50, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
