# Generated by Django 5.1.6 on 2025-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chek_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
