# Generated by Django 5.1.6 on 2025-05-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chek_in',
            new_name='Check_in',
        ),
    ]
