# Generated by Django 5.2.3 on 2025-06-24 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='category_photos', verbose_name='Photo')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('state', models.BooleanField(verbose_name='State')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('made_by', models.CharField(max_length=150, verbose_name='Made by')),
                ('weight_mark', models.CharField(choices=[('kg', 'kg'), ('piece', 'dona'), ('litr', 'litr'), ('box', 'quti')], max_length=20)),
                ('weight', models.BigIntegerField(verbose_name='Weight')),
                ('photo', models.ImageField(upload_to='category_photos', verbose_name='Photo')),
                ('serial_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')])),
                ('made_on', models.DateField(verbose_name='Made on')),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('state', models.BooleanField(verbose_name='State')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
